# Generated by Django 4.2.7 on 2026-07-31 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_abonnement_historiquepaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entreprise_validee', 'Entreprise validée'), ('entreprise_refusee', 'Entreprise refusée'), ('nouveau_message', 'Nouveau message'), ('nouveau_contact', 'Nouveau contact'), ('entreprise_favori', 'Ajouté aux favoris'), ('abonnement_expire', 'Abonnement expiré'), ('system', 'Notification système')], max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('est_lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
