# Generated by Django 4.2.7 on 2026-07-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_saved_entreprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='min_ca',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='CA minimum'),
        ),
        migrations.AddField(
            model_name='alert',
            name='secteur',
            field=models.CharField(blank=True, max_length=50, verbose_name="Secteur d'activité"),
        ),
    ]
