# Generated by Django 4.2.7 on 2026-08-01 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_temoignage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_alerte', models.CharField(max_length=200, verbose_name="Nom de l'alerte")),
                ('secteur', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('prix_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('prix_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ca_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('ca_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nombre_employes_min', models.IntegerField(blank=True, null=True)),
                ('nombre_employes_max', models.IntegerField(blank=True, null=True)),
                ('type_transaction', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('frequence', models.CharField(choices=[('immediat', 'Immédiat'), ('quotidien', 'Quotidien'), ('hebdomadaire', 'Hebdomadaire')], default='immediat', max_length=20)),
                ('derniere_notification', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerte de recherche',
                'verbose_name_plural': 'Alertes de recherche',
                'ordering': ['-created_at'],
            },
        ),
    ]
