# Generated by Django 4.2.7 on 2026-08-01 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alerterecherche'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('sujet', models.CharField(blank=True, choices=[('question', 'Question générale'), ('support', 'Support technique'), ('abonnement', 'Abonnement'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('ferme', 'Fermé')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('reponse', models.TextField(blank=True, verbose_name='Réponse')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
