# Generated by Django 4.2.7 on 2026-07-12 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('region', models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('sousse', 'Sousse'), ('sfax', 'Sfax'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('autre', 'Autre')], max_length=50, verbose_name='Région')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('prix_demande', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix demandé (TND)')),
                ('chiffre_affaires', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Chiffre d'affaires (TND)")),
                ('resultat_net', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Résultat net (TND)')),
                ('valeur_actifs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur des actifs (TND)')),
                ('endettement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Endettement (TND)')),
                ('nombre_employes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'employés")),
                ('annee_creation', models.IntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('surface_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface du local (m²)')),
                ('equipements_inclus', models.TextField(blank=True, verbose_name='Équipements inclus')),
                ('type_transaction', models.CharField(choices=[('vente_totale', 'Vente totale'), ('vente_partielle', 'Vente partielle'), ('recherche_associe', "Recherche d'associé"), ('levee_fonds', 'Levée de fonds')], default='vente_totale', max_length=30, verbose_name='Type de transaction')),
                ('points_forts', models.TextField(blank=True, verbose_name='Points forts')),
                ('opportunites_developpement', models.TextField(blank=True, verbose_name='Opportunités de développement')),
                ('nom_masque', models.BooleanField(default=False, verbose_name="Masquer le nom de l'entreprise")),
                ('adresse_masquee', models.BooleanField(default=False, verbose_name="Masquer l'adresse exacte")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('refusee', 'Refusée'), ('vendue', 'Vendue')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('est_mise_en_avant', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entreprises/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('is_logo', models.BooleanField(default=False, verbose_name='Logo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entreprises.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': "Image d'entreprise",
                'verbose_name_plural': "Images d'entreprise",
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/', verbose_name='Document')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entreprises.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['-created_at'], name='entreprises_created_40dae3_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['statut'], name='entreprises_statut_b6fb0b_idx'),
        ),
    ]
