# Generated by Django 4.2.7 on 2026-07-31 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('secteur', models.CharField(choices=[('industrie', 'Industrie'), ('agriculture', 'Agriculture'), ('services', 'Services'), ('commerce', 'Commerce'), ('tourisme', 'Tourisme et hôtellerie'), ('transport', 'Transport et logistique'), ('sante', 'Santé'), ('informatique', "Technologies de l'information"), ('education', 'Éducation'), ('btp', 'BTP et construction'), ('franchise', 'Franchise'), ('startup', 'Startups'), ('autre', 'Autres activités économiques')], max_length=50, verbose_name="Secteur d'activité")),
                ('region', models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('le_kef', 'Le Kef'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili')], max_length=50, verbose_name='Région')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('historique', models.TextField(blank=True, verbose_name="Historique de l'entreprise")),
                ('prix_demande', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix demandé (TND)')),
                ('chiffre_affaires', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Chiffre d'affaires (TND)")),
                ('resultat_net', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Résultat net (TND)')),
                ('valeur_actifs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valeur des actifs (TND)')),
                ('endettement', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Endettement (TND)')),
                ('nombre_employes', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Nombre d'employés")),
                ('annee_creation', models.IntegerField(blank=True, null=True, verbose_name='Année de création')),
                ('surface_local', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surface du local (m²)')),
                ('equipements_inclus', models.TextField(blank=True, verbose_name='Équipements inclus')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='URL vidéo de présentation')),
                ('type_transaction', models.CharField(choices=[('vente_totale', 'Vente totale'), ('vente_partielle', 'Vente partielle'), ('recherche_associe', "Recherche d'associé"), ('levee_fonds', 'Levée de fonds')], default='vente_totale', max_length=30, verbose_name='Type de transaction')),
                ('points_forts', models.TextField(blank=True, verbose_name='Points forts')),
                ('opportunites_developpement', models.TextField(blank=True, verbose_name='Opportunités de développement')),
                ('nom_masque', models.BooleanField(default=False, verbose_name="Masquer le nom de l'entreprise")),
                ('adresse_masquee', models.BooleanField(default=False, verbose_name="Masquer l'adresse exacte")),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('publiee', 'Publiée'), ('refusee', 'Refusée'), ('vendue', 'Vendue')], default='brouillon', max_length=20, verbose_name='Statut')),
                ('raison_refus', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('est_mise_en_avant', models.BooleanField(default=False, verbose_name='Mise en avant (premium)')),
                ('nombre_vues', models.PositiveIntegerField(default=0, verbose_name='Nombre de vues')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='entreprises/images/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('is_logo', models.BooleanField(default=False, verbose_name='Logo principal')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='entreprises.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='entreprises/documents/', verbose_name='Document PDF')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du document')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entreprises.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
