# Generated by Django 4.2.7 on 2026-07-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='historique',
            field=models.TextField(blank=True, verbose_name="Historique de l'entreprise"),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='raison_refus',
            field=models.TextField(blank=True, verbose_name='Raison du refus'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='secteur',
            field=models.CharField(choices=[('industrie', 'Industrie'), ('agriculture', 'Agriculture'), ('services', 'Services'), ('commerce', 'Commerce'), ('tourisme', 'Tourisme et hôtellerie'), ('transport', 'Transport et logistique'), ('sante', 'Santé'), ('informatique', 'Informatique et technologie'), ('education', 'Éducation et formation'), ('btp', 'BTP et construction'), ('franchise', 'Franchise'), ('startup', 'Startup'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name="Secteur d'activité"),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='region',
            field=models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('le_kef', 'Le Kef'), ('siliana', 'Siliana'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('kairouan', 'Kairouan'), ('kasserine', 'Kasserine'), ('sidi_bouzid', 'Sidi Bouzid'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili')], max_length=50, verbose_name='Région'),
        ),
    ]
