# Generated by Django 4.2.7 on 2026-07-31 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entreprises', to=settings.AUTH_USER_MODEL, verbose_name='Vendeur'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['-created_at'], name='entreprises_created_40dae3_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['statut'], name='entreprises_statut_b6fb0b_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['secteur'], name='entreprises_secteur_ed19ec_idx'),
        ),
        migrations.AddIndex(
            model_name='entreprise',
            index=models.Index(fields=['region'], name='entreprises_region_84d8c9_idx'),
        ),
    ]
