# Generated by Django 4.2.7 on 2026-07-22 19:12

import apps.entreprises.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0002_entreprise_historique_entreprise_raison_refus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube, Vimeo ou autre', max_length=500, verbose_name='URL de la vidéo de présentation'),
        ),
        migrations.AlterField(
            model_name='entreprisedocument',
            name='document',
            field=models.FileField(upload_to='documents/', validators=[apps.entreprises.validators.validate_document_file], verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='entrepriseimage',
            name='image',
            field=models.ImageField(upload_to='entreprises/', validators=[apps.entreprises.validators.validate_image_file], verbose_name='Image'),
        ),
    ]
