# Generated by Django 4.2.7 on 2026-07-31 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entreprises', '0004_favori'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatistiqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('vue', 'Vue de la page'), ('contact', 'Clic sur contact'), ('favori', 'Ajout aux favoris'), ('partage', 'Partage'), ('document', 'Téléchargement document'), ('image', 'Vue image')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='entreprises.entreprise')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_entreprises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Statistique Action',
                'verbose_name_plural': 'Statistiques Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre_vues', models.IntegerField(default=0)),
                ('nombre_vues_uniques', models.IntegerField(default=0)),
                ('temps_moyen_secondes', models.IntegerField(default=0)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques_vues', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Statistique Vue',
                'verbose_name_plural': 'Statistiques Vues',
                'ordering': ['-date'],
                'unique_together': {('entreprise', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StatistiqueConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nombre_vues', models.IntegerField(default=0)),
                ('nombre_contacts', models.IntegerField(default=0)),
                ('taux_conversion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='entreprises.entreprise')),
            ],
            options={
                'verbose_name': 'Statistique Conversion',
                'verbose_name_plural': 'Statistiques Conversions',
                'ordering': ['-date'],
                'unique_together': {('entreprise', 'date')},
            },
        ),
    ]
