# Generated by Django 4.2.7 on 2026-07-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0005_statistiqueaction_statistiquevue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='date_debut_mise_en_avant',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date début mise en avant'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='date_fin_mise_en_avant',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date fin mise en avant'),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='est_mise_en_avant',
            field=models.BooleanField(default=False, verbose_name='Mise en avant'),
        ),
    ]
