# Generated by Django 4.2.7 on 2026-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0007_actualite'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='messages/attachments/', verbose_name='Pièce jointe'),
        ),
    ]
